### ISSUE TITLE
font not found if folder matches font file name

### ISSUE THREAD

**Issue by hariedo** [mminer/hierarchy-icons#1]
Love the extension.

If there is any other asset (such as the folder you put the files in) which matches your HierarchyIcons name, the font is not found and you get letters instead.

I think your call to `.First()` in **IconDisplay.cs** s responsible, making an assumption.

`var guid = AssetDatabase.FindAssets(name).First();`

**Comment by mminer** [comment]
Thanks for the bug report, I’ll look into a fix ASAP.
